sudo: true
dist: trusty

jobs:
  include:
    - stage: build docker image
      script:
      - docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"
      - docker build -t client ./client
      - docker images
      - docker tag client $DOCKER_USERNAME/client
      - docker push $DOCKER_USERNAME/client

