dist: trusty

jobs:
  include:
    - stage: build docker image
      script:
      - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
      - docker build -t client ./client
      - docker images
      - docker tag client $DOCKER_USERNAME/client
      - docker push $DOCKER_USERNAME/client

